### ISSUE TITLE
Creation of Function Hierarchy Diagram

### ISSUE THREAD

**Issue by ceski23** [tania-sila-robocza/Meblex-Docs#1]
![IMG_20190402_131028](https://user-images.githubusercontent.com/2845072/55398534-17b19b80-5549-11e9-894f-d2096468b3a8.jpg)
![IMG_20190402_131023](https://user-images.githubusercontent.com/2845072/55398581-2f891f80-5549-11e9-8c14-8aaacbb6c78a.jpg)

**Comment by ceski23** [comment]
You can use https://www.draw.io/

**Comment by olome13** [comment]
![Function Hierarchy Diagram](https://user-images.githubusercontent.com/48941253/55405099-9c0c1a80-5559-11e9-9c82-4eb9a1151112.png)
Done.
